export const products = {
    1: {
        name: "iPhone 15",
        category: "Electronics",
        subcategory: "Smartphones",
        serialnumber: "A12345",
        price: 1000,
        discount: 10,
        stock: 50,
        description: "The latest iPhone with advanced features.",
        warranty: 12,
        distributername: "Apple",
        comments: ["Great phone!", "Expensive but worth it."],
        features: {
            screen: "6.1 inches",
            camera: "12 MP",
            storage: "128 GB",
            color: "Black"
        },
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-plus-blue-select-202309?wid=940&hei=1112&fmt=png-alpha&.v=1692991073037",
    },
    2: {
        name: "MacBook Pro",
        category: "Electronics",
        subcategory: "Laptops",
        serialnumber: "M12345",
        price: 2000,
        discount: 5,
        stock: 30,
        description: "Powerful laptop for professionals.",
        warranty: 12,
        distributername: "Apple",
        comments: ["Best laptop ever!", "A bit pricey."],
        features: {
            screen: "13.3 inches",
            processor: "Apple M1",
            storage: "512 GB",
            color: "Space Gray"
        },
        image: "https://cdsassets.apple.com/live/SZLF0YNV/images/sp/111339_sp818-mbp13touch-space-select-202005.png",
    },
    3: {
        name: "Samsung Galaxy S23",
        category: "Electronics",
        subcategory: "Smartphones",
        serialnumber: "S12345",
        price: 2000,
        discount: 5,
        stock: 0,
        description: "Flagship smartphone from Samsung.",
        warranty: 12,
        distributername: "Samsung",
        comments: ["Amazing camera!", "Battery life could be better."],
        features: {
            screen: "6.8 inches",
            camera: "108 MP",
            storage: "256 GB",
            color: "Phantom Black"
        },
        image: "https://m.media-amazon.com/images/I/616QJ8FeFVL.jpg",
    },
    4: {
        name: "Sony WH-1000XM4",
        category: "Electronics",
        subcategory: "Headphones",
        serialnumber: "S67890",
        price: 350,
        discount: 15,
        stock: 100,
        description: "Noise-cancelling over-ear headphones.",
        warranty: 24,
        distributername: "Sony",
        comments: ["Best noise cancellation!", "Comfortable to wear."],
        features: {
            batteryLife: "30 hours",
            noiseCancellation: "Yes",
            wireless: "Yes",
            color: "Black"
        },
        image: "https://cdn.cimri.io/image/1200x1200/sony-wh-1000xm4-siyah-bluetooth-kulaklik_933676905.jpg",
    },
    5: {
        name: "Dell XPS 13",
        category: "Electronics",
        subcategory: "Laptops",
        serialnumber: "D12345",
        price: 1500,
        discount: 10,
        stock: 0,
        description: "Ultra-thin and lightweight laptop.",
        warranty: 12,
        distributername: "Dell",
        comments: ["Great for travel!", "Excellent display."],
        features: {
            screen: "13.4 inches",
            processor: "Intel Core i7",
            storage: "1 TB",
            color: "Platinum Silver"
        },
        image: "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/dell/thumb/148682-2_large.jpg",
    },
    6: {
        name: "Apple Watch Series 8",
        category: "Electronics",
        subcategory: "Wearables",
        serialnumber: "AW12345",
        price: 400,
        discount: 5,
        stock: 80,
        description: "Advanced smartwatch with health features.",
        warranty: 12,
        distributername: "Apple",
        comments: ["Great fitness tracker!", "Battery lasts all day."],
        features: {
            screen: "1.9 inches",
            batteryLife: "18 hours",
            waterResistance: "Yes",
            color: "Midnight"
        },
        image: "https://ffo3gv1cf3ir.merlincdn.net//SiteAssets/pasaj/crop/cg/00C45P/1-1663828722639/1-1663828722639_600x450.png?1741182684000",
    },
    7: {
        name: "Canon EOS R5",
        category: "Electronics",
        subcategory: "Cameras",
        serialnumber: "C12345",
        price: 3800,
        discount: 0,
        stock: 10,
        description: "Professional mirrorless camera.",
        warranty: 12,
        distributername: "Canon",
        comments: ["Incredible image quality!", "Expensive but worth it for professionals."],
        features: {
            sensor: "45 MP",
            videoResolution: "8K",
            lensMount: "RF Mount",
            color: "Black"
        },
        image: "https://i1.adis.ws/i/canon/eos-r5_front_rf24-105mmf4lisusm_square_32c26ad194234d42b3cd9e582a21c99b?$prod-gallery-1by1-jpg$",
    },
    8: {
        name: "Bose QuietComfort 45",
        category: "Electronics",
        subcategory: "Headphones",
        serialnumber: "B12345",
        price: 329,
        discount: 10,
        stock: 60,
        description: "Premium noise-cancelling headphones.",
        warranty: 12,
        distributername: "Bose",
        comments: ["Super comfortable!", "Great sound quality."],
        features: {
            batteryLife: "24 hours",
            noiseCancellation: "Yes",
            wireless: "Yes",
            color: "Black"
        },
        image: "https://m.media-amazon.com/images/I/51HHABMPoVL._AC_UF1000,1000_QL80_.jpg",
    },
    9: {
        name: "LG OLED C1",
        category: "Electronics",
        subcategory: "TVs",
        serialnumber: "L12345",
        price: 2000,
        discount: 20,
        stock: 15,
        description: "4K OLED TV with stunning picture quality.",
        warranty: 24,
        distributername: "LG",
        comments: ["Best TV I've ever owned!", "Perfect for gaming."],
        features: {
            screenSize: "65 inches",
            resolution: "4K",
            smartTV: "Yes",
            color: "Black"
        },
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROjvl1_vkFf2NCwUAYz8uHaVQczbudD_u_xw&s",
    },
    10: {
        name: "Nintendo Switch",
        category: "Electronics",
        subcategory: "Gaming",
        serialnumber: "N12345",
        price: 299,
        discount: 0,
        stock: 40,
        description: "Hybrid gaming console.",
        warranty: 12,
        distributername: "Nintendo",
        comments: ["Fun for the whole family!", "Portable and versatile."],
        features: {
            screenSize: "6.2 inches",
            storage: "32 GB",
            color: "Neon Red/Blue"
        },
        image: "https://cdn.cimri.io/image/1000x1000/nintendo-switch-neon-red-blue-oyun-konsolu_622599579.jpg",
    }
};